version: 2.1
description: Build and test my repo  
executors:
  default:
    docker:
    - image: node:alpine
jobs: 
  build:
    description: Install dependencies, build, test
    executor: default
    steps:
    - run:
        name: Install dependencies
        command: npm run install
    - run:
        name: Build
        command: npm run build --if-present
    - run:
        name: Test
        command: npm run test
