version: 2.1
description: Build and test my repo  
executors:
  default:
    docker:
    - image: circleci/node:latest
jobs: 
  build:
    description: Install dependencies, build, test
    executor: default
    steps:
    - run:
        name: Install dependencies
        command: yarn install
    - run:
        name: Build
        command: yarn build
    - run:
        name: Test
        command: yarn test
