version: 2.1 # https://circleci.com/docs/2.0/configuration-reference/#version
description: Build and test my repo  
executors: # https://circleci.com/docs/2.0/configuration-reference/#executors-requires-version-21
  default:
    docker:
    - image: node:alpine
orbs: 
  sb: sandbox-jm/sandbox@0.0.1
jobs: # https://circleci.com/docs/2.0/configuration-reference/#jobs
  build:
    description: Install dependencies, build, test
    executor: default
    steps:
    - sb/hello